# The image will be at ghcr.io/yourusername/name
name: zind-home-server
# The native container image to build on top of
# images. 
# Warning: Non-uBlue images might function unexpectly
base-container: ghcr.io/ublue-os/base-main
# What fedora version to use. Use an explicit version or `latest`.
# If you use `latest`, you will be automatically updated
# to the next major version assuming the image you're using as your base container
# builds with the tag (all uBlue images do this). 
fedora-version: 38
# This description will be visible in the container metadata
description: Zindswini's uBlue based home server image
# These rpms will be installed from the fedora repository
# using rpm-ostree and will be preinstalled in the final image
rpms:
  - cinnamon
  - sddm
  - sddm-themes
  - openvpn
  - wireguard-tools
  - python3-pip # needed for yafti (the first boot installer)
  - cockpit-ws
  - cockpit-storaged
  - cockpit-networkmanager
  - cockpit-ostree
  - cockpit-podman
  - cockpit-selinux
  - cockpit-sosreport
  - cockpit-navigator
  - cockpit-benchmark
  - cockpit-sensors
  - btop
  - podman-compose
  - tmux
  - vim
  - duperemove
# These Flatpaks (from flathub) will be available for install on boot
# this is just an example selection.
# If you leave this empty you can use yafti for post-boot installation
flatpaks:
  - org.mozilla.firefox
  - org.gnome.DejaDup
  - org.gustavoperedo.FontDownloader
  - com.github.tchx84.Flatseal
  - io.github.celluloid_player.Celluloid
  - org.blender.Blender
  - fr.handbrake.ghb
  - org.videolan.VLC
